# https://docs.docker.com/engine/reference/commandline/compose_up
services:
  database:
    image: postgres:alpine
    container_name: superdupergallery-database
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgresql_data:
