# https://docs.docker.com/engine/reference/commandline/compose_up
version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: bearmentor-database
    hostname: database
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env

volumes:
  mysql_data:
